### PR TITLE
Improve Python 2 compatibility.

### PR DESCRIPTION
**Pull request by rmc3**
Including the following:
- Work around namespace changes in urllib/urlparse when ImportError is thrown.
- Fall back on Python 2-style super() invocation when TypeError is thrown.

See #30

### CODE REVIEW

**Comment by rmc3** [comment]
No tests have been run against this change set. I noticed that the README says:

> Builds must pass (which should be pretty easy right now, since there are no tests).

If there are tests I should be running, just point me to them and I'll do so!

**Comment by theherk** [comment]
That was written at a point when there were no tests and has not been updated. There are tests now. You can run them with `python setup.py test`. Also, this is looking good, but I don't think you need to try and except around the `super` calls. You can just do it the Python 2 way as that is fully acceptable in Python 3, too.

**Comment by rmc3** [comment]
Updated to only use Python 2's super() style, tests pass:

```
======================================================== test session starts ========================================================
platform darwin -- Python 3.5.1, pytest-3.0.2, py-1.4.31, pluggy-0.3.1
rootdir: /Users/richardchatterton/git-co/pinkopy, inifile:
collected 9 items

tests/pinkopy/test_base_session.py ....
tests/pinkopy/test_commvault.py ...
tests/pinkopy/test_exceptions.py ..

===================================================== 9 passed in 0.14 seconds ======================================================
```

**Comment by theherk** [comment]
Are there further changes you require? If so, I can leave this PR open while you update it. If you are good, I'll go ahead and merge.

**Comment by rmc3** [comment]
All of the functionality I need right now appears to work with these changes. We should be good to merge.

**Comment by theherk** [comment]
Okay, work from your local branch for now. I will get this done today, but I need to do some verification, and it is a crazy busy day.

**Comment by rmc3** [comment]
No problem! I don't have any packaging needs around this, I plan to install via Git for the forseeable future anyway. Thanks for your time.

**Comment by theherk** [comment]
I had forgotten to get this merged and release. Done now. Sorry for the delay.

https://pypi.python.org/pypi/pinkopy/2.1.2

**Pull request merged**
